config:
  data:
    batch_size: 1024
    caches_dir: /home/jia/MA/IMUDB-main/EuRoC/Preload
    data_dir: /home/jia/MA/IMUDB-main/EuRoC/Raw
    mask:
      mask_alpha: 6
      mask_prob: 0.8
      mask_ratio: 0.15
      max_gram: 10
      replace_prob: 0.0
    shuffle:
      test: true
      train: true
      val: true
    test_seqs:
    - MH_02_easy
    - MH_04_difficult
    - V2_02_medium
    - V1_03_difficult
    - V1_01_easy
    train_seqs:
    - MH_01_easy
    - MH_05_difficult
    - V2_01_easy
    - V2_03_difficult
    - MH_03_medium
    - V1_02_medium
    val_seqs:
    - MH_02_easy
    - MH_04_difficult
    - V2_02_medium
    - V1_03_difficult
    - V1_01_easy
  datasets_name: euroc_imudb
  experiment_management_log: experiments/experiment_management_log.csv
  experiment_name: imudb
  logs_dir: logs
  model:
    hyper_params:
      T_0: 5000
      T_mult: 10
      continuity_loss_weight: 2
      denoise_loss_weights: 10
      emb_norm: true
      eta_min: 1e-8
      feature_num: 6
      hidden: 72
      hidden_ff: 144
      mlm_loss_weights: 1
      n_heads: 4
      n_layers: 4
      nn_arch: limu_bert
      nsp_loss_weights: 1
      seq_len: 120
      starting_learning_rate: 0.001
      weight_decay: 1e-5
    inputs:
      imu_sequence_number: 30
    onnx:
      inputs:
      - x_imu
      outputs:
      - hat_imu
    outputs:
      imu_sequence_number: 30
  note: bug fix use raw and pred for nsp, weight denoise loss with 10
  sensors:
    cam0:
      frequency: 20
      info: global-shutter, monochrome
      model: MT9V034
    ground_truth:
      frequency: 20
      pose:
        frequency: 100
        methods: vicon
      position:
        error_bound: 0.001
        frequency: 20
        methods: Leica MS50
    imu:
      frequency: 200
      info: MEMS based, intrinsic calibrated
      model: ADIS16448
    synhronization: hardware-synchronized
  stage: dev
